run:
  timeout: 5m

version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - gochecknoinits
    - errcheck
    - copyloopvar
  settings:
    govet:
      enable:
        - shadow
    revive:
      confidence: 0.1
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    lll:
      line-length: 140
    misspell:
      locale: US
    staticcheck:
      checks: 
        - "all"
        - "-QF1007"
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: 'package-comments: should have a package comment'
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      - linters:
          - dupl
        path: _test\.go
      - linters:
          - dupl
        path: 'atomic.*\.go'
      - linters:
          - gosec
        path: auth_test\.go
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
