// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/iden3/go-iden3-auth/state (interfaces: GISTGetter)

// Package mock_state is a generated GoMock package.
package mock_state

import (
	big "math/big"
	reflect "reflect"

	bind "github.com/ethereum/go-ethereum/accounts/abi/bind"
	gomock "github.com/golang/mock/gomock"
	abi "github.com/iden3/contracts-abi/state/go/abi"
)

// MockGISTGetter is a mock of GISTGetter interface.
type MockGISTGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGISTGetterMockRecorder
}

// MockGISTGetterMockRecorder is the mock recorder for MockGISTGetter.
type MockGISTGetterMockRecorder struct {
	mock *MockGISTGetter
}

// NewMockGISTGetter creates a new mock instance.
func NewMockGISTGetter(ctrl *gomock.Controller) *MockGISTGetter {
	mock := &MockGISTGetter{ctrl: ctrl}
	mock.recorder = &MockGISTGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGISTGetter) EXPECT() *MockGISTGetterMockRecorder {
	return m.recorder
}

// GetGISTRootInfo mocks base method.
func (m *MockGISTGetter) GetGISTRootInfo(arg0 *bind.CallOpts, arg1 *big.Int) (abi.IStateGistRootInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGISTRootInfo", arg0, arg1)
	ret0, _ := ret[0].(abi.IStateGistRootInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGISTRootInfo indicates an expected call of GetGISTRootInfo.
func (mr *MockGISTGetterMockRecorder) GetGISTRootInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGISTRootInfo", reflect.TypeOf((*MockGISTGetter)(nil).GetGISTRootInfo), arg0, arg1)
}
